### ISSUE TITLE
Duplicate event categories reported

### ISSUE THREAD

**Issue by yogeshbeniwal** [xwp/site-performance-tracker#47] opened 2021-12-16 11:51 UTC
It seems duplicate event categories are reported, one as Web Vitals and other as general. Any particular reason for general category?

![Screenshot](https://user-images.githubusercontent.com/7325107/146366663-2d469635-73e9-409e-918b-63061e4a34fd.png)

**Comment by mehigh** [comment] 2022-03-10 08:50
@yogeshbeniwal 
We think this was caused by an incorrect logic in the JS, which was causing other side effects, like duplicating the page views being reported in particular cases
https://github.com/xwp/site-performance-tracker/pull/52/files

Can you try again with the latest released version https://github.com/xwp/site-performance-tracker/releases/tag/v1.1.2 and report back if this is still a problem for you?

Thank you!

**Comment by kasparsd** [comment] 2022-03-10 16:15
Marking as fixed in #52 for now. Please re-open if the issue is still present.

**Closed by kasparsd** 2022-03-10 16:15 UTC
Labels: bug
